"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _dashboard from './dashboard.bones.json'
import _brain_dump from './brain-dump.bones.json'
import _focus_mode from './focus-mode.bones.json'
import _goals from './goals.bones.json'
import _habits from './habits.bones.json'
import _journal from './journal.bones.json'
import _tasks from './tasks.bones.json'
import _timeline from './timeline.bones.json'

configureBoneyard({"color":"#d4d4d8","animate":"pulse"})

registerBones({
  "dashboard": _dashboard,
  "brain-dump": _brain_dump,
  "focus-mode": _focus_mode,
  "goals": _goals,
  "habits": _habits,
  "journal": _journal,
  "tasks": _tasks,
  "timeline": _timeline,
})
